on:
  pull_request:
    branches: [ master ]


jobs:
	@@ -16,3 +14,5 @@ jobs:

      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.0.0
        with:
          config_file: changelog-ci-config.json
